name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        feature_set:
          - ""
          - "async,serde,macros,anyhow,userdata-wrappers"
          - "async,serde,macros,anyhow,userdata-wrappers,send"
          - "luau-jit,async,serde,macros,anyhow,userdata-wrappers,send"
          - "luau-vector4,async,serde,macros,anyhow,userdata-wrappers,send"
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -p ruau --features "${{ matrix.feature_set }}"
        shell: bash

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]
        feature_set:
          - ""
          - "async,serde,macros,anyhow,userdata-wrappers"
          - "async,serde,macros,anyhow,userdata-wrappers,send"
          - "luau-jit,async,serde,macros,anyhow,userdata-wrappers,send"
          - "luau-vector4,async,serde,macros,anyhow,userdata-wrappers,send"
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test -p ruau --features "${{ matrix.feature_set }}"
        shell: bash

  test_with_sanitizer:
    name: Test with address sanitizer
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests with address sanitizer
        run: cargo test -p ruau --tests --features "async,serde,macros,anyhow,userdata-wrappers" -- --skip test_too_many_recursions
        shell: bash
        env:
          RUSTFLAGS: -Z sanitizer=address

  test_with_memory_limit:
    name: Test with memory limit
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests with forced memory limit
        run: cargo test -p ruau --tests --features "async,send,serde,macros,anyhow,userdata-wrappers"
        shell: bash
        env:
          RUSTFLAGS: --cfg=force_memory_limit

  test_modules:
    name: Test modules
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Run module tests
        run: |
          (cd crates/ruau/tests/module && cargo build --release)
          (cd crates/ruau/tests/module/loader && cargo test --release)
        shell: bash

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          clippy_flags: -p ruau --features "luau-jit,async,send,serde,macros,anyhow,userdata-wrappers"
